### ISSUE TITLE
some packages not found error on Arch Linux

### ISSUE THREAD

**Issue by Nusk-Rbb** [Andrea055/kali-on-ubuntu#3]
# Target Not found Error on Arch Linux
I tried this script on Arch Linux and found this target not found error, so I have opened an issue.
```bash
error: target not found: arping
error: target not found: hping3
error: target not found: copy-router-config
error: target not found: rtpflood
error: target not found: rtpinsertsound
error: target not found: rtpmixsound
error: target not found: httrack.
error: target not found: jsql
error: target not found: mdb-sql
error: target not found: sqldic
error: target not found: tnscmd10g
error: target not found: wordlists
error: target not found: statsgen
error: target not found: chirp
error: target not found: mfterm
error: target not found: ettercap-graphical
error: target not found: wireshark
error: target not found: proxychains4
error: target not found: miredo
error: target not found: stunnel4
error: target not found: extundelete
error: target not found: pst-utils
error: target not found: rifiuti
error: target not found: calpel
```

Most of the errors could be fixed by changing the package name to the correct package name by searching on blackarch or AUR, but  `copy-router-config`, `rtpinsertsound`, `rtpmixsound`, `statsgen`, and `pst-utils` are not found. did not come up just by searching. 

I was able to resolve the rest of the package and would like to Pull Request the current stage of the fix script.

**Comment by andreock** [comment]
ok, open a PR, I will review it and fix others packages that are not found. Thank you

**Comment by Nusk-Rbb** [comment]
Could you give me the authority to push a locally created branch?
